apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-test
  namespace: default
  annotations:
    github.com/project-slug: Kyejoon-Lee/backstage-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/guests
  lifecycle: experimental