site_name: 'backstage-test'
site_description: 'Main documentation for the helm upload example'
repo_url: https://github.com/Kyejoon-Lee/backstage-test
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'