apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: helm-upload-template
  title: Helm Chart Upload Template
  description: Upload a Helm chart to a repository with starter selection
spec:
  owner: hj537@naver.com
  type: service

  parameters:
    - title: Chart Info
      required:
        - chartName
        - version
        - deploymentType
      properties:
        chartName:
          title: Chart Name
          type: string
          description: Name of the Helm chart
        version:
          title: Chart Version
          type: string
          description: Version of the Helm chart
        deploymentType:
          title: Deployment Type
          type: string
          enum: [dev, stage, prod, qa]

    - title: Starter and Values Selection
      required:
        - starterType
        - valuesFile
      properties:
        starterType:
          title: Starter Type
          type: string
          description: Choose a starter folder
          enum: [basic, dp]
        valuesFile:
          title: Values File
          type: string
          description: Select a values file
      dependencies:
        starterType:
          oneOf:
            - properties:
                starterType:
                  const: basic
                valuesFile:
                  enum: [values.yaml, ginger-starter-values.yaml]
            - properties:
                starterType:
                  const: dp
                valuesFile:
                  enum: [dp-starter-values.yaml]

    - title: Optional File Upload
      properties:
        uploadFile:
          title: Additional File
          type: string
          format: data-url
          description: Optional file to upload (e.g., custom values.yaml)
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./starter/${{ parameters.starterType }}
        targetPath: ./charts/${{ parameters.chartName }}/${{ parameters.deploymentType }}/${{ parameters.version }}
        values:
          chartName: ${{ parameters.chartName }}
          version: ${{ parameters.version }}
          deploymentType: ${{ parameters.deploymentType }}
          valuesFile: ${{ parameters.valuesFile }}

    - id: copy-values-file
      name: Copy Selected Values File
      action: fs:write
      input:
        path: ./charts/${{ parameters.chartName }}/${{ parameters.deploymentType }}/${{ parameters.version }}/values.yaml
        content: |
          # Values file: ${{ parameters.valuesFile }}
          # This would contain the contents of ${{ parameters.valuesFile }}
          # TODO: Load actual file content from starter/${{ parameters.starterType }}/${{ parameters.valuesFile }}

    - id: copy-upload
      name: Save Uploaded File (if provided)
      if: ${{ parameters.uploadFile }}
      action: fs:write
      input:
        path: ./charts/${{ parameters.chartName }}/${{ parameters.deploymentType }}/${{ parameters.version }}/uploaded-file.yaml
        content: ${{ parameters.uploadFile }}
        encoding: base64

    - id: publish
      name: Publish to Repository
      action: publish:github
      input:
        description: "Helm chart ${{ parameters.chartName }} v${{ parameters.version }}"
        repoUrl: github.com?owner=example&repo=helm-charts
        defaultBranch: main

  output:
    links:
      - title: View in GitHub
        url: https://github.com/example/helm-charts
