apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: helm-upload-template
  title: Helm Chart Upload Template
  description: Upload a Helm chart to a repository with starter selection
spec:
  owner: hj537@naver.com
  type: service

  parameters:
    - title: Chart Info
      required:
        - chartName
        - version
        - deploymentType
      properties:
        chartName:
          title: Chart Name
          type: string
          description: Name of the Helm chart
        version:
          title: Chart Version
          type: string
          description: Version of the Helm chart
        deploymentType:
          title: Deployment Type
          type: string
          enum: [dev, stage, prod, qa]

    - title: Starter Selection
      required:
        - starterType
      properties:
        starterType:
          title: Starter Type
          type: string
          description: Choose a starter folder
          enum: [basic, dp]

    - title: Values File Selection
      description: Choose a values file based on your starter selection
      allOf:
        - if:
            properties:
              starterType:
                const: basic
          then:
            properties:
              valuesFile:
                title: Values File
                type: string
                enum: [values.yaml, ginger-starter-values.yaml]
                enumNames: ["Basic Values", "Ginger Starter Values"]
            required: [valuesFile]
        - if:
            properties:
              starterType:
                const: dp
          then:
            properties:
              valuesFile:
                title: Values File
                type: string
                enum: [dp-starter-values.yaml]
                enumNames: ["DP Starter Values"]
            required: [valuesFile]

    - title: Optional File Upload
      properties:
        uploadFile:
          title: Additional File
          type: string
          format: data-url
          description: Optional file to upload (e.g., custom values.yaml)
  steps:
    - id: copy-starter
      name: Copy Starter to Charts
      action: fs:copy
      input:
        files:
          - from: ./starter/${{ parameters.starterType }}
            to: ./charts/${{ parameters.chartName }}/${{ parameters.deploymentType }}/${{ parameters.version }}

    - id: copy-upload
      name: Save Uploaded File (if provided)
      if: ${{ parameters.uploadFile }}
      action: fs:write
      input:
        path: ./charts/${{ parameters.chartName }}/${{ parameters.deploymentType }}/${{ parameters.version }}/uploaded-file.yaml
        content: ${{ parameters.uploadFile }}
        encoding: base64

    - id: commit-and-push
      name: Commit & Push to Git
      action: git:commitAndPush
      input:
        repoUrl: github.com?owner=example&repo=helm-charts
        branch: main
        commitMessage: "Add chart ${{ parameters.chartName }} v${{ parameters.version }}"

  output:
    links:
      - title: View in GitHub
        url: https://github.com/example/helm-charts
