apiVersion: v1
entries:
  test-upload:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-08-18T09:37:12.266267492Z"
    description: A Helm chart for Kubernetes
    digest: a3a72e49f0106a48a1e1914c08a6c01ccae826ae5e9a64861de16f2e3bf34fde
    name: test-upload
    type: application
    urls:
    - test-upload-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-18T09:37:12.261859908Z"
