name: CI & CD dev
run-name: CI/CD - dev

on:
  push:
    branches: [ "main" ]
    paths:
      - 'charts/**'  # starter 디렉토리가 포함된 변경사항만 트리거

# 동시성 제어: 같은 브랜치에서는 하나의 워크플로우만 실행
concurrency:
  group: helm-operations-${{ github.ref }}
  cancel-in-progress: false  # 진행 중인 작업을 취소하지 않고 대기

jobs:
  helm-operations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 전체 히스토리를 가져와서 변경사항 감지

    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm

    - name: Verify Helm installation
      run: helm version

    - name: Detect new charts
      id: detect-charts
      run: |
        # 새롭게 추가된 charts/{name}/{env}/{version} 디렉토리 감지 (환경은 가변적)
        BASE_SHA="${{ github.event.before }}"
        
        # Git diff로 새로 추가된 charts 디렉토리 찾기 (환경 이름은 가변적)
        NEW_CHARTS=$(git diff --name-only --diff-filter=A $BASE_SHA HEAD | grep -E '^charts/[^/]+/[^/]+/[^/]+/' | cut -d'/' -f1-4 | sort -u || true)
        
        echo "Detected new charts:"
        echo "$NEW_CHARTS"
        
        # 결과를 환경 변수로 저장
        echo "NEW_CHARTS<<EOF" >> $GITHUB_OUTPUT
        echo "$NEW_CHARTS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Process and commit charts individually
      if: steps.detect-charts.outputs.NEW_CHARTS != ''
      run: |
        echo "Processing new charts individually..."
        
        # 새로 감지된 각 차트에 대해 개별적으로 처리
        while IFS= read -r chart_path; do
          if [ -n "$chart_path" ]; then
            echo "Processing: $chart_path"
            
            # charts/{name}/{env}/{version} 경로에서 name, env, version 추출
            name=$(echo "$chart_path" | cut -d'/' -f2)
            env=$(echo "$chart_path" | cut -d'/' -f3)
            version=$(echo "$chart_path" | cut -d'/' -f4)
            
            echo "Chart name: $name, Environment: $env, Version: $version"
            
            # 최신 변경사항을 가져와서 충돌 방지
            git fetch origin main
            git reset --hard origin/main
            
            # 1. charts/{name}/{env}/{version} 디렉토리로 이동하여 helm create 실행
            cd "$chart_path"
            
            # starter 디렉토리가 있는지 확인하고 helm create 실행
            if [ -d "./starter" ]; then
              echo "Creating chart using local starter directory"
              STARTER_PATH=$(pwd)/starter
              helm create --starter "$STARTER_PATH" "$name"
              
              # starter 디렉토리 삭제
              echo "Removing starter directory..."
              rm -rf "./starter"
            else
              echo "No starter directory found, creating default chart"
              helm create "$name"
            fi
            
            # 2. charts/{name}/{env}/{version}/{name} 안에서 helm lint 실행
            cd "$name"
            echo "Running helm lint for $name..."
            
            helm lint . --values override-values.yaml
            
            # 3. helm dependency build, package, repo index 실행
            echo "Building dependencies, packaging, and indexing..."
            helm dependency build ./
            helm package ./
            helm repo index ./
            
            echo "Completed processing for $name in $env environment"
            cd "$GITHUB_WORKSPACE"
            
            # 개별 차트 처리 후 즉시 커밋
            git add "$chart_path"
            if ! git diff --staged --quiet; then
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git commit -m "chore: process helm chart $name in $env environment (v$version)"
              
              # Push with retry logic for conflicts
              for i in {1..3}; do
                if git push origin main; then
                  echo "Successfully pushed changes for $name"
                  break
                else
                  echo "Push failed, attempt $i/3. Fetching latest changes..."
                  git fetch origin main
                  git rebase origin/main
                fi
              done
            fi
            
          fi
        done <<< "${{ steps.detect-charts.outputs.NEW_CHARTS }}"
